export enum LanguageCodes {
  English = 'eng',
  Spanish = 'spa',
  Chinese = 'zho',
  Hindi = 'hin',
  Arabic = 'ara',
  Portuguese = 'por',
  Bengali = 'ben',
  Russian = 'rus',
  Japanese = 'jpn',
  Punjabi = 'pan',
  German = 'deu',
  Javanese = 'jav',
  Korean = 'kor',
  French = 'fra',
  Telugu = 'tel',
  Marathi = 'mar',
  Tamil = 'tam',
  Urdu = 'urd',
  Italian = 'ita',
  Turkish = 'tur',
  Vietnamese = 'vie',
  Polish = 'pol',
  Ukrainian = 'ukr',
  Dutch = 'nld',
  Greek = 'ell',
  Swedish = 'swe',
  Thai = 'tha',
  Czech = 'ces',
  Romanian = 'ron',
  Hungarian = 'hun',
}
const Languages: Record<LanguageCodes, string> = {
  [LanguageCodes.English]: 'English',
  [LanguageCodes.Spanish]: 'Spanish',
  [LanguageCodes.Chinese]: 'Chinese',
  [LanguageCodes.Hindi]: 'Hindi',
  [LanguageCodes.Arabic]: 'Arabic',
  [LanguageCodes.Portuguese]: 'Portuguese',
  [LanguageCodes.Bengali]: 'Bengali',
  [LanguageCodes.Russian]: 'Russian',
  [LanguageCodes.Japanese]: 'Japanese',
  [LanguageCodes.Punjabi]: 'Punjabi',
  [LanguageCodes.German]: 'German',
  [LanguageCodes.Javanese]: 'Javanese',
  [LanguageCodes.Korean]: 'Korean',
  [LanguageCodes.French]: 'French',
  [LanguageCodes.Telugu]: 'Telugu',
  [LanguageCodes.Marathi]: 'Marathi',
  [LanguageCodes.Tamil]: 'Tamil',
  [LanguageCodes.Urdu]: 'Urdu',
  [LanguageCodes.Italian]: 'Italian',
  [LanguageCodes.Turkish]: 'Turkish',
  [LanguageCodes.Vietnamese]: 'Vietnamese',
  [LanguageCodes.Polish]: 'Polish',
  [LanguageCodes.Ukrainian]: 'Ukrainian',
  [LanguageCodes.Dutch]: 'Dutch',
  [LanguageCodes.Greek]: 'Greek',
  [LanguageCodes.Swedish]: 'Swedish',
  [LanguageCodes.Thai]: 'Thai',
  [LanguageCodes.Czech]: 'Czech',
  [LanguageCodes.Romanian]: 'Romanian',
  [LanguageCodes.Hungarian]: 'Hungarian',
};
