/* eslint-disable no-unused-vars */
export enum MODEL_NAMES {
  auth = 'auth',
  profile = 'profile',
  permission = 'permission',
  role = 'role',
  lap = 'lap',
  subscription = 'subscription',
  subscription_plan = 'subscription_plan',
  subscription_plan_feature = 'subscription_plan_feature',
  subscription_plan_feature_value = 'subscription_plan_feature_value',
  subscription_plan_feature_value_option = 'subscription_plan_feature_value_option',
  subscription_plan_feature_value_option_value = 'subscription_plan_feature_value_option_value',
  subscription_plan_feature_value_option_value_item = 'subscription_plan_feature_value_option_value_item',
  sample= 'sample',
  sample_result = 'sample_result',
  sample_result_item = 'sample_result_item',
  sample_media = 'sample_media',
  sample_media_item = 'sample_media_item',
  sample_notification = 'sample_notification',
  // product = 'product',
  // chat_room = 'chat_room',
  // translation = 'translation',
  // chat_message = 'chat_message',
  // product_like = 'product_like',
  // role_permission = 'role_permission',
}
