/* eslint-disable no-unused-vars */
export enum MODEL_NAMES {
  auth = 'users',
  profile = 'profiles',
  permission = 'permissions',
  role = 'roles',
  lap = 'laps',
  subscription = 'subscriptions',
  subscription_plan = 'subscription_plans',
  subscription_plan_feature = 'subscription_plan_features',
  subscription_plan_feature_value = 'subscription_plan_feature_values',
  subscription_plan_feature_value_option = 'subscription_plan_feature_value_options',
  subscription_plan_feature_value_option_value = 'subscription_plan_feature_value_option_values',
  subscription_plan_feature_value_option_value_item = 'subscription_plan_feature_value_option_value_items',
  sample = 'samples',
  sample_result = 'sample_results',
  sample_result_item = 'sample_result_items',
  sample_media = 'sample_medias',
  sample_media_item = 'sample_media_items',
  sample_notification = 'sample_notifications',
  patient = 'patients',
  role_permission = 'role_permissions',
  // product = 'product',
  // chat_room = 'chat_room',
  // translation = 'translation',
  // chat_message = 'chat_message',
  // product_like = 'product_like',
}
